# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import continuous_batcher_pb2 as continuous__batcher__pb2


class ContinuousBatcherStub(object):
    """The continuous batcher service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNeedNum = channel.unary_unary(
                '/continuous_batching.ContinuousBatcher/GetNeedNum',
                request_serializer=continuous__batcher__pb2.BatchingRequest.SerializeToString,
                response_deserializer=continuous__batcher__pb2.BatchingReply.FromString,
                )


class ContinuousBatcherServicer(object):
    """The continuous batcher service definition.
    """

    def GetNeedNum(self, request, context):
        """Sends a reply containing the actual batch size.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContinuousBatcherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNeedNum': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNeedNum,
                    request_deserializer=continuous__batcher__pb2.BatchingRequest.FromString,
                    response_serializer=continuous__batcher__pb2.BatchingReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'continuous_batching.ContinuousBatcher', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ContinuousBatcher(object):
    """The continuous batcher service definition.
    """

    @staticmethod
    def GetNeedNum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/continuous_batching.ContinuousBatcher/GetNeedNum',
            continuous__batcher__pb2.BatchingRequest.SerializeToString,
            continuous__batcher__pb2.BatchingReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
