# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: continuous_batcher.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63ontinuous_batcher.proto\x12\x13\x63ontinuous_batching\"#\n\x0f\x42\x61tchingRequest\x12\x10\n\x08need_num\x18\x01 \x01(\x05\"*\n\rBatchingReply\x12\x19\n\x11\x61\x63tual_batch_size\x18\x01 \x01(\x05\x32m\n\x11\x43ontinuousBatcher\x12X\n\nGetNeedNum\x12$.continuous_batching.BatchingRequest\x1a\".continuous_batching.BatchingReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'continuous_batcher_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BATCHINGREQUEST']._serialized_start=49
  _globals['_BATCHINGREQUEST']._serialized_end=84
  _globals['_BATCHINGREPLY']._serialized_start=86
  _globals['_BATCHINGREPLY']._serialized_end=128
  _globals['_CONTINUOUSBATCHER']._serialized_start=130
  _globals['_CONTINUOUSBATCHER']._serialized_end=239
# @@protoc_insertion_point(module_scope)
